# Generated by Django 5.2.17 on 2026-10-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200, verbose_name='razón social')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('distrito', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('licencia_url', models.TextField(blank=True, null=True, verbose_name='licencia (URL)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='motivo de rechazo')),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'botica',
                'verbose_name_plural': 'boticas',
                'db_table': 'botica',
                'ordering': ['-creado_en'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('principio_activo', models.CharField(max_length=150)),
                ('presentacion', models.CharField(max_length=100, verbose_name='presentación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('stock_minimo', models.IntegerField(default=5, verbose_name='stock mínimo')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
                'ordering': ['nombre_comercial'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(choices=[('COMPRADOR', 'Comprador'), ('DUENO_BOTICA', 'Dueño de botica')], max_length=20)),
                ('correo_verificado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
    ]
